projects:
  wspieramprzyrode:
    schemaPath: amplify/backend/api/wspieramprzyrode/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/core/services/graphql.service.ts
        docsFilePath: src/graphql
        region: eu-west-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
